### ISSUE TITLE
I've a little problem.

### ISSUE THREAD

**Issue by naoestu** [lCesarl/Lysium_Loginterface#1]
Syserr after installing everything:

0519 20:31:02488 :: Traceback (most recent call last):

0519 20:31:02488 ::   File "uiPhaseCurtain.py", line 58, in OnUpdate

0519 20:31:02488 ::   File "networkModule.py", line 157, in __ChangePhaseWindow

0519 20:31:02488 ::   File "introLogin.py", line 93, in Open

0519 20:31:02488 ::   File "introLogin.py", line 247, in SetChannel

0519 20:31:02488 ::   File "introLogin.py", line 329, in __LoadACCNames

0519 20:31:02488 :: AttributeError
0519 20:31:02488 :: : 
0519 20:31:02488 :: 'pack_file' object has no attribute 'close'
0519 20:31:02488 :: 

Any possible solution?

**Comment by naoestu** [comment]
Solved!

Solution:
Removed all "f.close()" from intrologin.py file.
